version: "3.3"
services:

  consul:
    image: consul:1.9.1
    command: ["consul","agent","-config-file=/config/consul-config.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
      - "./consul_data:/data"
    ports:
      - 8500:8500
      - 18600:8600
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  orderapp:
    build:
      context: ./order-ms
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 5000:5000
  orderapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-orderapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "order-ms"]
    network_mode: "service:orderapp"

  invoiceapp:
    build:
      context: ./invoice-ms
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 5001:5000
  invoiceapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-invoiceapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "invoice-ms"]
    network_mode: "service:invoiceapp"

  taxapp:
    build:
      context: ./tax-ms
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - 5002:5000
  taxapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-taxapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "tax-ms"]
    network_mode: "service:taxapp"

  # prometheus-server:
  #   image: prom/prometheus
  #   ports:
  #     - 9999:9090
  #   volumes:
  #     - ./prometheus-envoy-intensions-demo.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     vpcbr:
  #       ipv4_address: 10.5.0.9

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
